sudo: required
dist: bionic
language: csharp
solution: TaglibSharp.sln
mono: latest

# https://github.com/travis-ci/travis-ci/issues/5932#issuecomment-215693171
before_install:
  - mkdir -p .nuget
  - wget -O .nuget/nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - mono .nuget/nuget.exe # Output NuGet's version number

install:
  - sudo apt-get update -qq > /dev/null
    #  - mono .nuget/nuget.exe restore TaglibSharp.sln -Verbosity detailed
  - mono .nuget/nuget.exe install NUnit.Runners -Version 3.10.0 -OutputDirectory packages

script:
  - msbuild /restore TaglibSharp.sln
  - cd src/TaglibSharp.Tests/bin/Debug
  - mono ../../../../packages/NUnit.ConsoleRunner.3.10.0/tools/nunit3-console.exe --labels=All net461/TaglibSharp.Tests.dll